# Naming the workflow.
name: First Workflow

# Defining when this workflow will be executed.
on: workflow_dispatch

# Defining the work that will be done, that is all the jobs that will be executed in this workflow.
jobs:
  # Defining a job.
  first-job:
    # Defining the environment that will be used by this job.
    runs-on: ubuntu-latest
    # Defining the steps, that is the operations, the job will execute.
    steps:
      # Definins a step.
      # Every step defined must start with a dash "-".
        # name keyword labels the step, making it easier to understand that step purpose.
      - name: Print greeting
        # run keyword define what will be executed in the command line
        run: echo "Hello World!"
        
      - name: Print goodbye
        # To execute multiple shell commands, add a pipe symbol (|) as a value after the "run" keyword.
        run: |
            echo "Done - bye!"
            echo "See you later!"
    
